#--- Account level configs ---

account-macros:
  - name: Apply default account macros to all
    allow-groups:
      - characters-all
    file: default.txt

account-keybinding:
  - name: Apply 8 boomy resto druid
    allow-groups:
      - test
    file: default.txt

account-config:
  - name: test
    allow-groups:
      - test
    file: default.txt

account-saved-variables: # per account AddOns settings
  - name: test
    allow-groups:
      - test
    allow-addons:
      - AtlasLoot.lua
      - Combuctor.lua
      - Dominos.lua
      - Mappy.lua
      - oCC.lua
      - Omen.lua
      - PallyPower.lua
      - Parrot.lua
      - Postal.lua
      - Quartz.lua
      - RatingBuster.lua
      - Skada.lua
      - SlideBar.lua
      - HealBot.lua

#--- Character level configs ---
character-chat:
  - name: Apply default chat settings to all characters.
    allow-groups:
      - test
    ignore-groups: []
    file: default.txt

character-addons:
#  - name:
#    allow-groups:
#      - characters-all
#    ignore-groups: []
#    file: 09-sdm-only.txt

  #--- 平时模式:
#  - name:
#    allow-groups:
#      - addons-enable-all
#    ignore-groups: []
#    file: 01-enable-all.txt
#
#  - name: # 骑士主号
#    allow-groups:
#      - addons-single-player-comprehensive
#    ignore-groups: []
#    file: 03-single-player-comprehensive.txt
#
#  - name: # 德鲁伊 萨满 法师 牧师 术士 主号
#    allow-groups:
#      - addons-single-player-comprehensive-but-pallypower
#    ignore-groups: []
#    file: 04-single-player-comprehensive-but-pallypower.txt
#
#  - name:
#    allow-groups:
#      - addons-multibox-minimal-but-pallypower
#    ignore-groups: []
#    file: 06-multibox-minimal-but-pallypower.txt
#
#  - name:
#    allow-groups:
#      - addons-enable-all
#    ignore-groups: []
#    file: 01-enable-all.txt

  #--- 最少插件最大利用计算及性能极限多开模式
  - name:
    allow-groups:
      - addons-multibox-super-minimal
    ignore-groups: []
    file: 11-super-minimal.txt

  - name:
    allow-groups:
      - addons-multibox-super-minimal-but-pallypower
    ignore-groups: []
    file: 12-super-minimal-but-pallypower.txt


character-layout:
  # it is a "task"
  - name: Apply default Layout to all characters. Include chat frame, loot frame, action bar, caster bar, map position, etc ...
    allow-groups:
      - characters-all
    ignore-groups: []
    file: default.txt

character-macros:
#  - name: Apply balance resto dual spec druid character macro for multibox as slave
#    allow-groups:
#      - characters-8-dudu
#    file: druid-balance-resto-multibox-slave.txt
#  - name:
#    allow-groups:
#      - characters-warlock-pvp
#    file: warlock-demon-pvp-lv80.txt
  - name:
    allow-groups:
      - test
    file: priest-kangliu-shadow-pve-and-disco-pve-lv80.txt

character-keybinding:
  - name: Apply keybinding to warrior and dk only
    allow-groups:
      - keybinding-warrior-and-dk
    file: warrior-and-dk.txt
  - name: Apply default keybinding to all other than warrior and dk
    allow-groups:
      - characters-all
    ignore-groups:
      - keybinding-warrior-and-dk
    file: default.txt
#  - name: test
#    allow-groups:
#      - test
#    file: default.txt

character-config:
  - name: Apply default character config, include equipment manager, talent previewer and camera mode set
    allow-groups:
      - characters-all
    file: default.txt

character-saved-variables: # per character AddOns settings
  - name: test
    allow-groups:
      - test
    allow-addons:
      - Atlas.lua
      - AtlasLoot.lua
      - Vendomatic.lua
