# Syntax:
#
# Valid item name:
#
# - for character: ${AccountName}.${RealmName}.${CharacterName} case not sensitive
# - for group: ${GroupName}
#
# if you have group item defined in a group, all member of that group
# will be added to the parent group
#
# WARNING: make sure you don't have circular reference!


#--- group by accounts ---
accounts-fatmulti1:
  - Fatmulti1.Icecrown.BatleFury
  - Fatmulti1.Icecrown.Litgoatssa
  - Fatmulti1.Icecrown.Litgoatzsa
  - Fatmulti1.Icecrown.Litgoatdka
  - Fatmulti1.Icecrown.Litgoatdza

accounts-fatmulti2:
  - Fatmulti2.Icecrown.Quentinquinn
  - Fatmulti2.Icecrown.Litgoatssb
  - Fatmulti2.Icecrown.Litgoatzsb
  - Fatmulti2.Icecrown.Litgoatdkb
  - Fatmulti2.Icecrown.Litgoatdzb

accounts-fatmulti3:
  - Fatmulti3.Icecrown.Opiitou
  - Fatmulti3.Icecrown.Litgoatssc
  - Fatmulti3.Icecrown.Litgoatzsc
  - Fatmulti3.Icecrown.Litgoatdkc
  - Fatmulti3.Icecrown.Litgoatdzc

accounts-fatmulti4:
  - Fatmulti4.Icecrown.Swagsonic
  - Fatmulti4.Icecrown.Litgoatssd
  - Fatmulti4.Icecrown.Litgoatzsd
  - Fatmulti4.Icecrown.Litgoatdkd
  - Fatmulti4.Icecrown.Litgoatdzd

accounts-fatmulti5:
  - Fatmulti5.Icecrown.Kangliu
  - Fatmulti5.Icecrown.Litgoatsse
  - Fatmulti5.Icecrown.Litgoatzse
  - Fatmulti5.Icecrown.Litgoatdke
  - Fatmulti5.Icecrown.Litgoatdze

accounts-fitsheep:
  - Fitsheep.Icecrown.Kindhearted
  - Fitsheep.Icecrown.Bordercollie
  - Fitsheep.Icecrown.Sweetmonk
  - Fitsheep.Icecrown.Angorarabbit
  - Fitsheep.Icecrown.Sheepbunny
  - Fitsheep.Icecrown.Angrybunny
  - Fitsheep.Icecrown.Juicysheep
  - Fitsheep.Icecrown.Chunlily

accounts-fatmulti6:
  - Fatmulti6.Icecrown.Kapacuk
  - Fatmulti6.Icecrown.Litgoatssh
  - Fatmulti6.Icecrown.HealthyMonk
  - Fatmulti6.Icecrown.Litgoatxdh

accounts-fatmulti8:
  - Fatmulti8.Icecrown.Bunnysisters
  - Fatmulti8.Icecrown.Litgoatssi
  - Fatmulti8.Icecrown.Honeymonk
  - Fatmulti8.Icecrown.Litgoatxdi

accounts-fatmulti9:
  - Fatmulti9.Icecrown.Glowyy
  - Fatmulti9.Icecrown.Litgoatssj
  - Fatmulti9.Icecrown.ChubbyMonk
  - Fatmulti9.Icecrown.Litgoatxdj

accounts-fatmulti10:
  - Fatmulti10.Icecrown.Luxiaofeng
  - Fatmulti10.Icecrown.Litgoatssk
  - Fatmulti10.Icecrown.ShinyMonk
  - Fatmulti10.Icecrown.Litgoatxdk

accounts-makun7551:
  - Makun7551.Icecrown.Laoshou
  - Makun7551.Icecrown.Ganjj

accounts-fatmulti11:
  - Fatmulti11.Icecrown.Litgugua

accounts-fatmulti12:
  - Fatmulti12.Icecrown.Litgugub

accounts-fatmulti13:
  - Fatmulti13.Icecrown.Litguguc

accounts-fatmulti14:
  - Fatmulti14.Icecrown.Litgugud

accounts-fatmulti15:
  - Fatmulti15.Icecrown.Litgugue

accounts-fatmulti16:
  - Fatmulti16.Icecrown.Litguguf

accounts-fatmulti17:
  - Fatmulti17.Icecrown.Litgugug

accounts-fatmulti18:
  - Fatmulti18.Icecrown.Litguguh

accounts-fatmulti19:
  - Fatmulti19.Icecrown.lgmsi

accounts-fatmulti20:
  - Fatmulti20.Icecrown.lgmsj

accounts-fatmulti21:
  - Fatmulti21.Icecrown.lgmsk

accounts-fatmulti22:
  - Fatmulti22.Icecrown.lgmsl

accounts-fatmulti23:
  - Fatmulti23.Icecrown.lgsmm

accounts-fatmulti24:
  - Fatmulti24.Icecrown.lgsmn

accounts-fatmulti25:
  - Fatmulti25.Icecrown.lgsmo

accounts-fatmulti26:
  - Fatmulti26.Icecrown.lgsmp

#--- group by characters ---
characters-all:
  - accounts-fatmulti1
  - accounts-fatmulti2
  - accounts-fatmulti3
  - accounts-fatmulti4
  - accounts-fatmulti5
  - accounts-fitsheep
  - accounts-fatmulti6
  - accounts-fatmulti8
  - accounts-fatmulti9
  - accounts-fatmulti10
  - accounts-fatmulti11
  - accounts-fatmulti12
  - accounts-fatmulti13
  - accounts-fatmulti14
  - accounts-fatmulti15
  - accounts-fatmulti16
  - accounts-fatmulti17
  - accounts-fatmulti18
  - accounts-fatmulti19
  - accounts-fatmulti20
  - accounts-fatmulti21
  - accounts-fatmulti22
  - accounts-fatmulti23
  - accounts-fatmulti24
  - accounts-fatmulti25
  - accounts-fatmulti26

#--- by class
characters-warlock-pvp:
  - Fatmulti1.Icecrown.Litgoatssa
  - Fatmulti2.Icecrown.Litgoatssb
  - Fatmulti3.Icecrown.Litgoatssc
  - Fatmulti4.Icecrown.Litgoatssd
  - Fatmulti5.Icecrown.Litgoatsse

characters-high-gs:
  - Fatmulti1.Icecrown.BatleFury
  - Fatmulti2.Icecrown.Quentinquinn
  - Fatmulti3.Icecrown.Opiitou
  - Fatmulti4.Icecrown.Swagsonic
  - Fatmulti5.Icecrown.Kangliu
  - Fitsheep.Icecrown.Kindhearted
  - Fitsheep.Icecrown.Bordercollie
  - Fitsheep.Icecrown.Sweetmonk
  - Fatmulti6.Icecrown.Kapacuk
  - Fatmulti8.Icecrown.Bunnysisters
  - Fatmulti9.Icecrown.Glowyy
  - Fatmulti10.Icecrown.Luxiaofeng

characters-8-dudu:
  - Fatmulti11.Icecrown.Litgugua
  - Fatmulti12.Icecrown.Litgugub
  - Fatmulti13.Icecrown.Litguguc
  - Fatmulti14.Icecrown.Litgugud
  - Fatmulti15.Icecrown.Litgugue
  - Fatmulti16.Icecrown.Litguguf
  - Fatmulti17.Icecrown.Litgugug
  - Fatmulti18.Icecrown.Litguguh

characters-4-litgugua-to-litgugud:
  - Fatmulti11.Icecrown.Litgugua
  - Fatmulti12.Icecrown.Litgugub
  - Fatmulti13.Icecrown.Litguguc
  - Fatmulti14.Icecrown.Litgugud

characters-4-litgugue-to-litguguh:
  - Fatmulti15.Icecrown.Litgugue
  - Fatmulti16.Icecrown.Litguguf
  - Fatmulti17.Icecrown.Litgugug
  - Fatmulti18.Icecrown.Litguguh

#--- group by class ---
class-paladins:
  - Fatmulti1.Icecrown.BatleFury
  - Fatmulti9.Icecrown.Glowyy
  - Fatmulti6.Icecrown.HealthyMonk

#--- group by addons ---
addons-raid-mode-pala-tanks:
  - Fatmulti1.Icecrown.BatleFury

addons-raid-mode-non-pala-tanks:
  - Fatmulti10.Icecrown.Luxiaofeng

addons-raid-mode-pala-other-members:
  - Fatmulti9.Icecrown.Glowyy
  - Fatmulti6.Icecrown.HealthyMonk

addons-raid-mode-non-pala-other-members:
  - Fatmulti2.Icecrown.Quentinquinn
  - Fatmulti3.Icecrown.Opiitou
  - Fatmulti4.Icecrown.Swagsonic
  - Fatmulti5.Icecrown.Kangliu
  - Fitsheep.Icecrown.Kindhearted
  - Fatmulti6.Icecrown.Kapacuk
  - Fatmulti8.Icecrown.Bunnysisters
  - Fatmulti11.Icecrown.Litgugua
  - Fatmulti12.Icecrown.Litgugub
  - Fatmulti13.Icecrown.Litguguc
  - Fatmulti14.Icecrown.Litgugud
  - Fatmulti15.Icecrown.Litgugue
  - Fatmulti16.Icecrown.Litguguf
  - Fatmulti17.Icecrown.Litgugug
  - Fatmulti18.Icecrown.Litguguh
  - Fitsheep.Icecrown.Bordercollie
  - Fitsheep.Icecrown.Sweetmonk
  - Fatmulti8.Icecrown.Honeymonk
  - Fatmulti9.Icecrown.ChubbyMonk
  - Fatmulti10.Icecrown.ShinyMonk

addons-enable-all:
  # high gs main char
  - Fatmulti1.Icecrown.BatleFury
  - Fatmulti2.Icecrown.Quentinquinn
  - Fatmulti3.Icecrown.Opiitou
  - Fatmulti4.Icecrown.Swagsonic
  - Fatmulti5.Icecrown.Kangliu
  - Fitsheep.Icecrown.Kindhearted
  - Fatmulti6.Icecrown.Kapacuk
  - Fatmulti8.Icecrown.Bunnysisters
  - Fatmulti9.Icecrown.Glowyy
  - Fatmulti10.Icecrown.Luxiaofeng
  # others
  - Fitsheep.Icecrown.Bordercollie
  - Fitsheep.Icecrown.Sweetmonk
  # banker
  - Fitsheep.Icecrown.Angorarabbit

addons-enable-all-for-luxiaofeng:
  - Fatmulti10.Icecrown.Luxiaofeng

addons-multibox-minimal-for-non-luxiaofeng:
  - addons-multibox-minimal
  - Fitsheep.Icecrown.Kindhearted
  - Fatmulti6.Icecrown.Kapacuk
  - Fatmulti8.Icecrown.Bunnysisters
  - Fatmulti9.Icecrown.Glowyy

addons-multibox-minimal:
  - Fatmulti1.Icecrown.Litgoatssa
  - Fatmulti1.Icecrown.Litgoatzsa
  - Fatmulti1.Icecrown.Litgoatdka
  - Fatmulti1.Icecrown.Litgoatdza
  - Fatmulti2.Icecrown.Litgoatssb
  - Fatmulti2.Icecrown.Litgoatzsb
  - Fatmulti2.Icecrown.Litgoatdkb
  - Fatmulti2.Icecrown.Litgoatdzb
  - Fatmulti3.Icecrown.Litgoatssc
  - Fatmulti3.Icecrown.Litgoatzsc
  - Fatmulti3.Icecrown.Litgoatdkc
  - Fatmulti3.Icecrown.Litgoatdzc
  - Fatmulti4.Icecrown.Litgoatssd
  - Fatmulti4.Icecrown.Litgoatzsd
  - Fatmulti4.Icecrown.Litgoatdkd
  - Fatmulti4.Icecrown.Litgoatdzd
  - Fatmulti5.Icecrown.Litgoatsse
  - Fatmulti5.Icecrown.Litgoatzse
  - Fatmulti5.Icecrown.Litgoatdke
  - Fatmulti5.Icecrown.Litgoatdze
  - Fitsheep.Icecrown.Sheepbunny
  - Fitsheep.Icecrown.Angrybunny
  - Fitsheep.Icecrown.Juicysheep
  - Fitsheep.Icecrown.Chunlily
  - Fatmulti6.Icecrown.Litgoatssh
  - Fatmulti6.Icecrown.HealthyMonk
  - Fatmulti6.Icecrown.Litgoatxdh
  - Fatmulti8.Icecrown.Litgoatssi
  - Fatmulti8.Icecrown.Honeymonk
  - Fatmulti8.Icecrown.Litgoatxdi
  - Fatmulti9.Icecrown.Litgoatssj
  - Fatmulti9.Icecrown.ChubbyMonk
  - Fatmulti9.Icecrown.Litgoatxdj
  - Fatmulti10.Icecrown.Litgoatssk
  - Fatmulti10.Icecrown.ShinyMonk
  - Fatmulti10.Icecrown.Litgoatxdk
  - Fatmulti11.Icecrown.Litgugua
  - Fatmulti12.Icecrown.Litgugub
  - Fatmulti13.Icecrown.Litguguc
  - Fatmulti14.Icecrown.Litgugud
  - Fatmulti15.Icecrown.Litgugue
  - Fatmulti16.Icecrown.Litguguf
  - Fatmulti17.Icecrown.Litgugug
  - Fatmulti18.Icecrown.Litguguh


#--- group by keybinding ---
keybinding-warrior-and-dk:
  - Fitsheep.Icecrown.Sweetmonk
  - Fatmulti1.Icecrown.Litgoatdka
  - Fatmulti2.Icecrown.Litgoatdkb
  - Fatmulti3.Icecrown.Litgoatdkc
  - Fatmulti4.Icecrown.Litgoatdkd
  - Fatmulti5.Icecrown.Litgoatdke
  - Fatmulti10.Icecrown.Luxiaofeng

test:
#  - Makun7551.Icecrown.Ganjj
#  - Makun7551.Icecrown.Laoshou
  - Fatmulti19.Icecrown.lgmsi
  - Fatmulti20.Icecrown.lgmsj
  - Fatmulti21.Icecrown.lgmsk
  - Fatmulti22.Icecrown.lgmsl
  - Fatmulti23.Icecrown.lgsmm
  - Fatmulti24.Icecrown.lgsmn
  - Fatmulti25.Icecrown.lgsmo
  - Fatmulti26.Icecrown.lgsmp
